name: master_paper
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pip
  - pip:
    - argh
    - argon2-cffi
    - async-generator
    - attrs
    - backcall
    - bleach
    - certifi
    - cffi
    - charset-normalizer
    - cycler
    - debugpy
    - decorator
    - defusedxml
    - entrypoints
    - idna
    - importlib-metadata
    - ipykernel
    - ipython
    - ipython-genutils
    - ipywidgets
    - jedi
    - jinja2
    - joblib
    - jsonschema
    - jupyter
    - jupyter-client
    - jupyter-console
    - jupyter-core
    - jupyterlab-pygments
    - jupyterlab-widgets
    - kiwisolver
    - lxml
    - markupsafe
    - matplotlib
    - matplotlib-inline
    - mistune
    - nbclient
    - nbconvert
    - nbformat
    - nest-asyncio
    - networkx
    - notebook
    - numpy
    - packaging
    - pandas
    - pandocfilters
    - parso
    - pexpect
    - pickleshare
    - pillow
    - pkgtools
    - prometheus-client
    - prompt-toolkit
    - ptyprocess
    - pycparser
    - pygments
    - pyparsing
    - pyrsistent
    - python-dateutil
    - pytz
    - pyzmq
    - qtconsole
    - qtpy
    - requests
    - scikit-learn
    - scipy
    - send2trash
    - six
    - terminado
    - testpath
    - threadpoolctl
    - torch
    - tornado
    - tqdm
    - traitlets
    - typing-extensions
    - urllib3
    - wcwidth
    - webencodings
    - widgetsnbextension
    - zipp
